import Constants from 'expo-constants'

// Import from .env file (via react-native-dotenv)
// These will be undefined if .env file doesn't exist or variables aren't set
// @ts-ignore - @env is generated by react-native-dotenv
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '@env'

/**
 * Environment configuration for Expo
 * Priority:
 * 1. .env file (via @env) - RECOMMENDED for local development
 * 2. app.json extra field - Fallback for development
 * 
 * For production, use EAS Secrets or app.json (but be careful with secrets)
 */
export const ENV = {
  SUPABASE_URL: SUPABASE_URL || Constants.expoConfig?.extra?.supabaseUrl || '',
  SUPABASE_ANON_KEY: SUPABASE_ANON_KEY || Constants.expoConfig?.extra?.supabaseAnonKey || '',
}

if (!ENV.SUPABASE_URL || !ENV.SUPABASE_ANON_KEY) {
  console.warn(
    '⚠️ Missing Supabase environment variables.\n' +
    'Please set them in:\n' +
    '  1. .env file (recommended): SUPABASE_URL and SUPABASE_ANON_KEY\n' +
    '  2. OR app.json under "extra" section'
  )
} else {
  console.log('✅ Supabase environment variables loaded successfully')
}

